{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.5.jar",
          "url": "KotlinLibrary-2.0.5.jar",
          "size": 300974,
          "sha512": "c924780b1f094bbffd04ac8f063de9fe79cdd021a4daa936121bea9ecb6b610c970498e5ee8c02ff7d1a0c17e8401fd3a730f7537a57d86801452f992b1a57a4",
          "sha256": "773c58d023b11bcdeb7d6fb3d1438b3b92c94239b408dcb0c4290bef061fae32",
          "sha1": "40510e18f358865c31d9671c0a23f71d2bf01739",
          "md5": "87e887121934b384524f160baafe6bd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.5.jar",
          "url": "KotlinLibrary-2.0.5.jar",
          "size": 300974,
          "sha512": "c924780b1f094bbffd04ac8f063de9fe79cdd021a4daa936121bea9ecb6b610c970498e5ee8c02ff7d1a0c17e8401fd3a730f7537a57d86801452f992b1a57a4",
          "sha256": "773c58d023b11bcdeb7d6fb3d1438b3b92c94239b408dcb0c4290bef061fae32",
          "sha1": "40510e18f358865c31d9671c0a23f71d2bf01739",
          "md5": "87e887121934b384524f160baafe6bd7"
        }
      ]
    }
  ]
}
