{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.4.jar",
          "url": "KotlinLibrary-2.0.4.jar",
          "size": 300294,
          "sha512": "7f589d53fe80df82d0b71acdb62f4d1094c1c0d2b6011116cc6c9e701956391ef3837cd5b0aeff9801dfabe9462b5fc3ca528fe7e12e4cb0178c94a1ffbe496d",
          "sha256": "96bb32642319dce5d7b6ff7e333152bf07999d049733497eb755d59d9b3679d9",
          "sha1": "d0acebcfab646e7f46ea0a7ab13af29fb79c04cc",
          "md5": "47b029dc0cdd58f8b350c46f33c2d57f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.4.jar",
          "url": "KotlinLibrary-2.0.4.jar",
          "size": 300294,
          "sha512": "7f589d53fe80df82d0b71acdb62f4d1094c1c0d2b6011116cc6c9e701956391ef3837cd5b0aeff9801dfabe9462b5fc3ca528fe7e12e4cb0178c94a1ffbe496d",
          "sha256": "96bb32642319dce5d7b6ff7e333152bf07999d049733497eb755d59d9b3679d9",
          "sha1": "d0acebcfab646e7f46ea0a7ab13af29fb79c04cc",
          "md5": "47b029dc0cdd58f8b350c46f33c2d57f"
        }
      ]
    }
  ]
}
