{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.8.jar",
          "url": "KotlinLibrary-2.0.8.jar",
          "size": 315481,
          "sha512": "3cbe248041834756791e205e69aff0b187e72f6430142a30d342896f25f6e44a7642073fb94916d5c9b6e93ddbe4ab263d48a60a9c62842308f605887209779d",
          "sha256": "6e3817ed7df310dc991fc0967b7d91fbf133b03fd74d33dc38c5791f8619af71",
          "sha1": "8f6396810f9fa0f1b268861a4166d2c4af92283f",
          "md5": "86b7c7c122658932349e17137ef848c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.8.jar",
          "url": "KotlinLibrary-2.0.8.jar",
          "size": 315481,
          "sha512": "3cbe248041834756791e205e69aff0b187e72f6430142a30d342896f25f6e44a7642073fb94916d5c9b6e93ddbe4ab263d48a60a9c62842308f605887209779d",
          "sha256": "6e3817ed7df310dc991fc0967b7d91fbf133b03fd74d33dc38c5791f8619af71",
          "sha1": "8f6396810f9fa0f1b268861a4166d2c4af92283f",
          "md5": "86b7c7c122658932349e17137ef848c4"
        }
      ]
    }
  ]
}
