{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.11.jar",
          "url": "KotlinLibrary-2.0.11.jar",
          "size": 341708,
          "sha512": "5cefd3128868b901647f4b5ff0687547b291d21c2bb37524145a460580170b27452e0c3f13224e3f816cdd3b356b69cd3c2551000ab43896da1a328e2478b1dc",
          "sha256": "5263554907bfb7908398fad3719b9cbcab6daf58f088e63bcd831ed82ae69dd2",
          "sha1": "e63a934dad0abd62e32b2bf45acd44da29d11b40",
          "md5": "212a591d32d560cc4d863f5fd5124955"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.11.jar",
          "url": "KotlinLibrary-2.0.11.jar",
          "size": 341708,
          "sha512": "5cefd3128868b901647f4b5ff0687547b291d21c2bb37524145a460580170b27452e0c3f13224e3f816cdd3b356b69cd3c2551000ab43896da1a328e2478b1dc",
          "sha256": "5263554907bfb7908398fad3719b9cbcab6daf58f088e63bcd831ed82ae69dd2",
          "sha1": "e63a934dad0abd62e32b2bf45acd44da29d11b40",
          "md5": "212a591d32d560cc4d863f5fd5124955"
        }
      ]
    }
  ]
}
