{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.10.jar",
          "url": "KotlinLibrary-2.0.10.jar",
          "size": 314138,
          "sha512": "2abd29f7eb036365efc2c824eca46a244b00b1f7a2656a6bd459cb48f439ddf752796a53f42aa1e6124bc529cf5a9e5ce369449201d7f5106aa316c4d4238669",
          "sha256": "b52299434ae2f8d927181f9b18f28b47fe87f88e2cca6a52e366668e4eaa19c0",
          "sha1": "93925b45a2b25c5b599683a58f9cf3210b2ac7c2",
          "md5": "169c2883e30577613a84945419328bcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.10.jar",
          "url": "KotlinLibrary-2.0.10.jar",
          "size": 314138,
          "sha512": "2abd29f7eb036365efc2c824eca46a244b00b1f7a2656a6bd459cb48f439ddf752796a53f42aa1e6124bc529cf5a9e5ce369449201d7f5106aa316c4d4238669",
          "sha256": "b52299434ae2f8d927181f9b18f28b47fe87f88e2cca6a52e366668e4eaa19c0",
          "sha1": "93925b45a2b25c5b599683a58f9cf3210b2ac7c2",
          "md5": "169c2883e30577613a84945419328bcd"
        }
      ]
    }
  ]
}
