{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.9.jar",
          "url": "KotlinLibrary-2.0.9.jar",
          "size": 315504,
          "sha512": "a32b6ef8500aaef7397dccfe7fb244bcc638aecd668130b0924605aa641a60496a1f370cc46bb54666f82c71ddfa1eb049df4b155f06815e0ece7c131e304094",
          "sha256": "2b082573adfc039f9c693b3d3479b0f1a02845b3d2d56e89f5bf3aee69d4e467",
          "sha1": "4c24940530c7accee37b290609fb1c5bb45cf796",
          "md5": "437c507a472aa06b2430ac24b2812619"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.9.jar",
          "url": "KotlinLibrary-2.0.9.jar",
          "size": 315504,
          "sha512": "a32b6ef8500aaef7397dccfe7fb244bcc638aecd668130b0924605aa641a60496a1f370cc46bb54666f82c71ddfa1eb049df4b155f06815e0ece7c131e304094",
          "sha256": "2b082573adfc039f9c693b3d3479b0f1a02845b3d2d56e89f5bf3aee69d4e467",
          "sha1": "4c24940530c7accee37b290609fb1c5bb45cf796",
          "md5": "437c507a472aa06b2430ac24b2812619"
        }
      ]
    }
  ]
}
