{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "KotlinLibrary",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "KotlinLibrary-2.0.7.jar",
          "url": "KotlinLibrary-2.0.7.jar",
          "size": 305951,
          "sha512": "03a3973419bde91121098ddc7eed0e7e68fcb0fe9aef12efe6b46361b681a3eb77c0c4b5e0ce6dba8db2c841b0445d42dc37d18db6d8fd9b5de89d0b61917dac",
          "sha256": "4477576983171980a66965b2bf0cd71211523567212a8d76861e58dc84c0eeaf",
          "sha1": "bac68c51a597cd6d08cfd30ba2575e6f4218c913",
          "md5": "974d90b51dd72b8f47b7f26203ca55c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KotlinLibrary-2.0.7.jar",
          "url": "KotlinLibrary-2.0.7.jar",
          "size": 305951,
          "sha512": "03a3973419bde91121098ddc7eed0e7e68fcb0fe9aef12efe6b46361b681a3eb77c0c4b5e0ce6dba8db2c841b0445d42dc37d18db6d8fd9b5de89d0b61917dac",
          "sha256": "4477576983171980a66965b2bf0cd71211523567212a8d76861e58dc84c0eeaf",
          "sha1": "bac68c51a597cd6d08cfd30ba2575e6f4218c913",
          "md5": "974d90b51dd72b8f47b7f26203ca55c5"
        }
      ]
    }
  ]
}
